---
- hosts: droplet
  tasks:
    - name: Installs nginx web server
      sudo: true
      apt: pkg=nginx state=installed update_cache=true
      notify:
        - start nginx

  handlers:
    - name: start nginx
      sudo: true
      service: name=nginx state=started
